# Generated by Django 2.1.4 on 2018-12-26 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sketch', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(help_text='评论', max_length=200, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程评论',
                'verbose_name_plural': '课程评论',
            },
        ),
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_time', models.DateField(help_text='报名时间', verbose_name='报名时间')),
                ('pay_mount', models.FloatField(default=0.0, help_text='实际付款', verbose_name='实际付款')),
                ('preferential_channels', models.CharField(help_text='优惠渠道', max_length=200, verbose_name='优惠渠道')),
                ('know_yak', models.CharField(help_text='如何了解YaK', max_length=200, verbose_name='如何了解YaK')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('add_time', models.DateField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '销售信息',
                'verbose_name_plural': '销售信息',
            },
        ),
        migrations.CreateModel(
            name='SketchComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(help_text='留言', max_length=200, verbose_name='留言')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '作品评论',
                'verbose_name_plural': '作品评论',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(help_text='手机', max_length=11, verbose_name='手机')),
                ('course_name', models.CharField(help_text='课程名', max_length=50, verbose_name='课程名')),
                ('desc', models.CharField(help_text='描述', max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户咨询',
                'verbose_name_plural': '用户咨询',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户课程',
                'verbose_name_plural': '用户课程',
            },
        ),
        migrations.CreateModel(
            name='UserDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expired_time', models.DateTimeField(default='2019-01-02', help_text='使用过期时间', verbose_name='使用过期时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户使用期限',
                'verbose_name_plural': '用户使用期限',
            },
        ),
        migrations.CreateModel(
            name='UserEnroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='学生姓名', max_length=20, verbose_name='学生姓名')),
                ('birthday', models.DateField(blank=True, help_text='学生生日', null=True, verbose_name='学生生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', help_text='学生性别', max_length=6, verbose_name='学生性别')),
                ('mobile', models.CharField(blank=True, help_text='家长手机号', max_length=100, null=True, verbose_name='家长手机号')),
                ('address', models.CharField(blank=True, help_text='家庭住址', max_length=100, null=True, verbose_name='家庭住址')),
                ('school', models.CharField(blank=True, help_text='入读学校', max_length=100, null=True, verbose_name='入读学校')),
                ('enroll', models.CharField(blank=True, help_text='试听课时间选择', max_length=100, null=True, verbose_name='试听课时间选择')),
                ('msg_ad', models.CharField(choices=[('yes', '是'), ('no', '否')], default='no', help_text='是否愿意接受短信推广信息', max_length=3, verbose_name='是否愿意接受短信推广信息')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=200, null=True, verbose_name='备注')),
                ('add_time', models.DateField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '微信及网页版报名信息',
                'verbose_name_plural': '微信及网页版报名信息',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户收藏课程',
                'verbose_name_plural': '用户收藏课程',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户收藏机构',
                'verbose_name_plural': '用户收藏机构',
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteSketch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('sketch', models.ForeignKey(help_text='收藏的作品', on_delete=django.db.models.deletion.CASCADE, to='sketch.Sketch', verbose_name='作品')),
            ],
            options={
                'verbose_name': '用户收藏作品',
                'verbose_name_plural': '用户收藏作品',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, help_text='接受用户', verbose_name='接受用户')),
                ('message', models.CharField(help_text='消息内容', max_length=500, verbose_name='消息内容')),
                ('has_read', models.BooleanField(default=False, help_text='是否已读', verbose_name='是否已读')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
            },
        ),
    ]
