# Generated by Django 2.1.4 on 2018-12-27 09:14

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='课程名', max_length=50, verbose_name='课程名')),
                ('desc', models.CharField(help_text='课程简短描述', max_length=300, verbose_name='课程简短描述')),
                ('detail', DjangoUeditor.models.UEditorField(default='', help_text='课程详情', verbose_name='课程详情')),
                ('url', models.CharField(default='', help_text='课程介绍视频地址', max_length=200, verbose_name='课程介绍视频地址')),
                ('degree', models.IntegerField(choices=[(1, '1年级'), (2, '2年级'), (3, '3年级'), (4, '4年级'), (5, '5年级'), (6, '6年级'), (7, '初一'), (8, '初二'), (9, '初三'), (10, '高一'), (11, '高二'), (12, '高三'), (13, '大一'), (14, '大二'), (15, '大三'), (16, '大四'), (17, '成人')], default=3, help_text='难度', verbose_name='难度')),
                ('learn_times', models.IntegerField(default=0, help_text='学习时长(分钟)', verbose_name='学习时长(分钟)')),
                ('students', models.IntegerField(default=0, help_text='学习人数', verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(default=0, help_text='收藏人数', verbose_name='收藏人数')),
                ('image', models.ImageField(help_text='封面图', upload_to='courses/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, help_text='点击数', verbose_name='点击数')),
                ('category', models.CharField(default='数字艺术', help_text='课程类别', max_length=20, verbose_name='课程类别')),
                ('tag', models.CharField(default='', help_text='课程标签', max_length=10, verbose_name='课程标签')),
                ('youneed_know', models.CharField(default='', help_text='课程须知', max_length=300, verbose_name='课程须知')),
                ('teacher_tell', models.CharField(default='', help_text='能学到什么', max_length=300, verbose_name='能学到什么')),
                ('sold_num', models.IntegerField(default=0, help_text='已付款人数', verbose_name='课程销量')),
                ('goods_sn', models.CharField(default='', help_text='商品唯一货号', max_length=50, verbose_name='课程商品唯一货号')),
                ('market_price', models.FloatField(default=0, help_text='原价', verbose_name='市场价格')),
                ('shop_price', models.FloatField(default=0, help_text='促销价', verbose_name='促销价')),
                ('is_new', models.BooleanField(default=False, help_text='是否新品', verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, help_text='是否热销', verbose_name='是否热销')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='资源名称', max_length=100, verbose_name='资源名称')),
                ('download', models.FileField(help_text='资源文件', upload_to='courses/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('course', models.ForeignKey(help_text='课程', on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '课程资源',
                'verbose_name_plural': '课程资源',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='章节名', max_length=100, verbose_name='章节名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('course', models.ForeignKey(help_text='课程', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='章节内容名称', max_length=100, verbose_name='章节内容名称')),
                ('url', models.CharField(default='', help_text='章节内容访问地址', max_length=200, verbose_name='章节内容访问地址')),
                ('learn_times', models.IntegerField(default=0, help_text='学习时长(分钟)', verbose_name='学习时长(分钟)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('lesson', models.ForeignKey(help_text='章节', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name': '章节内容',
                'verbose_name_plural': '章节内容',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='视频名', max_length=100, verbose_name='视频名')),
                ('url', models.CharField(default='', help_text='章节视频访问地址', max_length=200, verbose_name='章节视频访问地址')),
                ('learn_times', models.IntegerField(default=0, help_text='学习时长(分钟)', verbose_name='学习时长(分钟)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间')),
                ('lesson', models.ForeignKey(help_text='章节', on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='章节')),
            ],
            options={
                'verbose_name': '章节视频',
                'verbose_name_plural': '章节视频',
            },
        ),
    ]
